# example values
server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: false

indexing-settings:
  sites:
    - url: https://Sendel.ru
      name: Константин Шибков

    - url: https://nopaper.ru
      name: Nopaper

#    - url: https://www.ipfran.ru
#      name: Ipfran.ru

#    - url: https://www.playback.ru
#      name: PlayBack.Ru
#    - url: https://www.dimonvideo.ru
#      name: Dimonvideo.ru
connection-config:
  user-agent: AnSeEn/1.0 (X11; Ubuntu; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0
  referer: http://www.google.com
  timeout: 0