# example values
server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

indexing-settings:
  sites:
#    - url: https://www.nashe.ru/
#      name: Наше Радио

    - url: https://Sendel.ru/
      name: Константин Шибков

#
#    - url: https://nopaper.ru/
#      name: Nopaper




#
#    - url: https://www.playback.ru/
#      name: PlayBack.Ru
connection-config:
  user-agent: AnSeEn/1.0 (X11; Ubuntu; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0
  referer: http://www.google.com
  timeout: 0